### ISSUE TITLE
Pre-prints in biology

### ISSUE THREAD

**Issue by lgatto** [sje30/schol2018#2]
Pre-prints are taking on in the biomedical field, but here's something that could be added to the pre-print section: [*The prehistory of biology preprints: A forgotten experiment from the 1960s.*](https://www.ncbi.nlm.nih.gov/pubmed/29145518), describing how publishers killed a predecessor of pre-prints. While not a recent perspective, it gives an interesting background on the current battle.

**Comment by sje30** [comment]
good idea.  I'll weave it in.

**Comment by sje30** [comment]
added.
